<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\AppIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="GameForm.Utils.cs" />
    <Compile Update="GameForm.Combat.cs" />
    <Compile Update="GameForm.Entities.cs" />
    <Compile Update="GameForm.Sprites.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="GameForm.Input.cs" />
    <Compile Update="GameForm.UI.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="GameForm.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Buffs\buff_armor.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Buffs\buff_crit_chance.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Buffs\buff_crit_mult.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Buffs\buff_hp.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Buffs\buff_multicast.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Buffs\buff_speed.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Buffs\buff_xp.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fon\Armagedon.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fon\Fon_Game.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\angel\afk_down_ang.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\angel\afk_left_ang.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\angel\afk_right_ang.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\angel\afk_up_ang.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\angel\angel_death.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\angel\walk_down.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\angel\walk_left.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\angel\walk_right.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\angel\walk_up.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_archer\arrow_down.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_archer\arrow_left.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_archer\arrow_right.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_archer\arrow_up.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_archer\shoot_archer_down.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_archer\shoot_archer_left.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_archer\shoot_archer_right.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_archer\shoot_archer_up.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_archer\walk_archer_down.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_archer\walk_archer_left.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_archer\walk_archer_right.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_archer\walk_archer_up.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_common\walk_down_d.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_common\walk_left_d.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_common\walk_right_d.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_common\walk_up_d.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_strong\walk_strong_down.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_strong\walk_strong_left.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_strong\walk_strong_right.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gifs_animation\demon_strong\walk_strong_up.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\10_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\11_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\12_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\13_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\14_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\15_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\16_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\17_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\18_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\19_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\1_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\20_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\21_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\22_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\23_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\24_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\25_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\26_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\27_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\28_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\29_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\2_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\30_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\3_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\4_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\5_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\6_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\7_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\8_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Skills\9_skill.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="StoryCharacters\Angel.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="StoryCharacters\Angel_full.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="StoryCharacters\Demon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="StoryCharacters\Demon_full.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
	<ItemGroup>
		<Content Include="gifs_animation\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="fon\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>